<?php

namespace App\Models;

use App\Observers\CategoryObserve;
use Astrotomic\Translatable\Translatable;
use Illuminate\Database\Eloquent\Model;

class category extends Model
{
    use Translatable;

    protected $with = ['translations'];

    protected $fillable = ['slug','is_active','parent_id'];

    protected $translatedAttributes = ['name'];
    protected $hidden = ['translations'];
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        category::observe(CategoryObserve::class);
    }

    protected $casts = [
        'is_active'=>'boolean',
    ];
    public function getActive()
    {
        return $this->is_active == '1' ?  __('admin/categories/index.active') :  __('admin/categories/index.inactive');
    }
    public function getImageAttribute($val)
    {
    return ($val !== null) ? asset($val) : '';
    }
    public function parent(){
        return $this->belongsTo(self::class , 'parent_id','id');
    }




}
